name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl --location --request POST https://api.github.com/repos/vitaTiZ/moreWorkFlows/dispatches \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Authorization: Basic ${{ secrets.MY_ENV.ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'